name: CD workflow
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.DROPLET_SSH_USER }}
          key: ${{ secrets.DROPLET_SSH_KEY }}
          script: |
            cd /var/www/facere-album
            docker-compose down
            git pull https://franciszek-szeptycki:${{ secrets.GH_API_TOKEN }}@github.com/franciszek-szeptycki/facere-album.git
            docker-compose -f docker-compose.prod.yml up -d --build
